FROM openjdk:17-jdk-slim

WORKDIR /
WORKDIR app

COPY target/wallet-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]

CMD ["run"]

ENV SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
ENV SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
ENV SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
ENV SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=${POSTGRES_SCHEMA}
